### ISSUE TITLE
Reservoir parameter fvol_over

### ISSUE THREAD

**Issue by tpilz** [TillF/WASA-SED#30]
As it seems, the parameter 'fvol_over' of reservoir.dat is wrongly described in the documentation.

The documentation says:

> Fraction of storage capacity that indicates the minimum storage volume for water release through the spillway of the sub-basin's reservoir [-]

whereas in the source code reservoir_h.f90, line 31 it is written:

> flag to simulate reservoir routing during spillway overflow of the sub-basin's reservoir [0 = without time delay; 1 = with time delay]

I discovered it because, when setting the parameter to a real number, an error was thrown as it declared as integer in the source code. This should be clarified.

Cheers,
Tobias

**Comment by TillF** [comment]
feel free to fix this. By now, you're probably the most competent person to do this.

**Comment by TillF** [comment]
fixed in Markdown-version of docu
