### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by shmulik90** [TillF/WASA-SED#65]
Hi,
I really didn't want to post this but after quite some time trying to fix this problem i am writing here to see whether you'd have the solution... im not that familiar with compiling but anyhow:

I use cygwin on a windows machine and try to compile the source code... but there seems to be an issue with the paths of the update_revision_no.bat file- i tried to get my head around it without success so far...

![grafik](https://user-images.githubusercontent.com/38791059/44484119-7d809100-a612-11e8-8421-93d42b8035f0.png)

**Comment by tpilz** [comment]
I am not a Windows guy but I have a suspicion. Can you simply swap lines 219 and 220 in the Makefile, try again and report? Maybe this already solves the issue.

**Comment by shmulik90** [comment]
I found that I had to change paths in the update_revision_no.bat file to absolute paths... now it compiles! 

The next question is: The provided tutorial files are supposed to run correctly? I get quite some errors of missing files / wrong dimensions if i try to run the provided InputTutorial model files...

**Comment by tpilz** [comment]
Unfortunately the tutorial has not been updated for many years now. I fear it is outdated by now. At the moment I don't think there is enough time to prepare a new tutorial / example.

However, you are welcome to send me an e-mail and I can send you some example data: tpilz@uni-potsdam.de
